-- begin CUBABI_BI_REPORT_ROLE
alter table CUBABI_BI_REPORT_ROLE add constraint FK_CUBABI_BIREPOROLE_REPORT foreign key (REPORT_ID) references CUBABI_BI_REPORT(ID)^
alter table CUBABI_BI_REPORT_ROLE add constraint FK_CUBABI_BI_REPORT_ROLE_ROLE foreign key (ROLE_ID) references SEC_ROLE(ID)^
create index IDX_CUBABI_BIREPOROLE_REPORT on CUBABI_BI_REPORT_ROLE (REPORT_ID)^
create index IDX_CUBABI_BIREPOROLE_ROLE on CUBABI_BI_REPORT_ROLE (ROLE_ID)^
-- end CUBABI_BI_REPORT_ROLE
